---
layout: single
title:  "자바 에러 처리"
categories: JAVA 
tag: [JAVA, try, catch, 에러처리,자바의 정석]
toc: true
author_profile: false
---

# 💡자바 에러 처리 

<!--Quote-->
> *본 내용은 자바의 정석을 바탕으로 작성*  

> ❗ 개인이 공부한 내용을 적은 것 이기에 오류가 많을 수도 있음 

# 2022-02-01

## 프로그램 오류

- 컴파일 에러 (Complie error) : 컴파일 할 때 발생하는 에러 → 코드쳤는데 발생 하는 에러(이클립스가 오류를 체크해줌)
- 런타임 에러 (Rutime error) : 실행 할 때 발생하는 에러 → 코드를 실행했는데 발생하는 에러, 프로그램 종료
- 논리적 에러 (logical error) : 작성 의도와 다르게 동작 → 프로그램 종료 x

## JAVA의 런타임 에러

- 에러(Error) : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외(Exception) : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

<details>
<summary>👈예외(Exception) 추가 설명</summary>
<div markdown="1">       
1. 예외는 Exception과 그 자손들 , RuntimeException과 그 자손들로 나누어진다.
2. Exception과 그자손들은 checked 예외다 (예외 처리 필수)
3. RuntimeException과 그 자손들은 unchecked 예외 (에러 처리 선택)
</div>
</details> 

## 예외 처리 try~catch

```java
try {
		// 예외가 발생할 가능성이 있는 문장을 넣는다 
} catch(Exception1 e1) {
		// 예외처리e1을 위한 문장을 적는다
} catch(Exception1 e2) {
		// 예외처리e2을 위한 문장을 적는다
} catch(Exception1 e3) {
		// 예외처리e3을 위한 문장을 적는다
} 
```

## printStackTrace와 getMessage

- printStackTrace() : 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메세지를 화면에 출력
- getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻음

```java
class Error_2 {
	public static void main(String args[]) {
		System.out.println(1);			
		System.out.println(2);

		try {
			System.out.println(3);
			System.out.println(0/0); // 예외발생!!!
			System.out.println(4);   // 실행되지 않는다.
		} catch (ArithmeticException ae)	{  // java.lang.ArithmeticException: / by zero
	at Ex8_5.main(Ex8_5.java:8) 
			ae.printStackTrace();
			System.out.println("예외메시지 : " + ae.getMessage()); // 예외메시지 : / by zero
		}	// try-catch의 끝

		System.out.println(6);
	}	// main메서드의 끝
}
```

## 예외 발생시키기

- 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
	Exception e = new Exception(”고의로 발생시킴”);
- 키워드  throw를 이용해서 예외를 발생시킨다.
	throw e;

```java
class ErrorThrow_2 {
	public static void main(String args[]) {
		try {
			Exception e = new Exception("고의로 발생시켰음.");
			throw e;	 // 예외를 발생시킴
		//  throw new Exception("고의로 발생시켰음.");

		} catch (Exception e)	{  // throw에서 던진걸 catch로 잡음 
			System.out.println("에러 메시지 : " + e.getMessage());
			e.printStackTrace();
		}
		System.out.println("프로그램이 정상 종료되었음.");
	}
}
```

## Finally

- 예외 발생여부와 관계없이 수행되어야 하는 코드를 넣는다.

```java
try {
		// 예외가 발생할 가능성이 있는 문장을 넣는다 
} catch(Exception1 e1) {
		// 예외처리를 위한 문장을 적는다
} finally {
		// 예외 발생여부에 관계없이 항상 수행되어야하는 문장들을 넣는다.
		// finally블럭은 try-catch문의 맨 마지막에 위치해야한다.
}
```

## 사용자 정의 예외

- 직접 예외 클래스 정의 가능
- 조상은 Exception과 RuntimeException 중에서 선택

```java
class MyException extends Exception {
			MyException(String msg) { // 문자열을 매개변수로 받는 생성자 
				super(msg); // 조상인 Exception클래스의 생성자 호출
		 }
}
```

## 예외 되던지기 (Exception re-throwing)

- 예외를 처리한 후에 다시 예외를 발생시키는 것
- 호출한 메서드와 호출된 메서드 양쪽 모두에서 예외처리하는 것

```java
class exception_re-throwing_2 {
	public static void main(String[] args) {
		try  {
			method1();	// 여기서 method1()을 호출 
		} catch (Exception e)	{
			System.out.println("main메서드에서 예외가 처리되었습니다."); // 최종 예외 처리
		}
	}	// main메서드의 끝

	static void method1() throws Exception {
		try {
			throw new Exception();    // 여기서 아래 catch로 전달 
		} catch (Exception e) {
			System.out.println("method1메서드에서 예외가 처리되었습니다.");
			throw e;			// 다시 예외를 발생시킨다. main의 try로 보냄 
		}
	}	// method1메서드의 끝
}
```

## 📑 출처 

 - [자바의 정석 카페](https://cafe.naver.com/javachobostudy) 
 - [자바의 정석 유튜브](https://www.youtube.com/user/MasterNKS)